# -*- coding: utf-8 -*-
"""AI_Exam3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unzEM68BtWlQXCgx--sdYWD_M45xlWZD
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt

training_data = np.array(
    [[0,0],[0,1],[1,0],[1,1]],'float32'
)
target_data = np.array(
    [[0],[1],[1],[0]],'float32')

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

# model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])
model.compile(loss='mse', optimizer='adam', metrics=['binary_accuracy'])
fit_hist = model.fit(training_data, target_data, epochs=500, verbose = 1)

plt.plot(fit_hist.history['loss'])
plt.show()

plt.plot(fit_hist.history['binary_accuracy'])
plt.show()

print(model.predict(np.array([[0,0]])))
print(model.predict(np.array([[0,1]])))
print(model.predict(np.array([[1,0]])))
print(model.predict(np.array([[1,1]])))

print(model.predict(np.array([[0,0]]))[0][0].round())
print(model.predict(np.array([[0,1]]))[0][0].round())
print(model.predict(np.array([[1,0]]))[0][0].round())
print(model.predict(np.array([[1,1]]))[0][0].round())