# -*- coding: utf-8 -*-
"""AI_exam06_iris_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Lo6aDJ7k2Rykh_M_Uk6BscIvVakLER7
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

iris = load_iris()
print(type(iris))
print('==================data shape==============')
print('Data', iris.data.shape)
print('Target', iris.target.shape)

print('First five data', iris.data[:5])
print('First five target', iris.target[:5])
print('iris dataset keys', iris.keys())
print('iris dataset target_names', iris.target_names)

print('iris feature name', iris.feature_names)

import pandas as pd
iris_dataframe = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_dataframe.head()

pd.plotting.scatter_matrix(iris_dataframe, c=iris.target, figsize=(7, 7),
                           marker='o', hist_kwds={'bins': 20}, s=60, alpha=.8)
plt.show()

x = iris.data
y = iris.target

y

encoder = OneHotEncoder(sparse_output=False)
encoded_y = encoder.fit_transform(y.reshape(-1, 1))
print(encoded_y.shape)
print(encoded_y[:5])

X_train, X_test, Y_train, Y_test = train_test_split(
    x, encoded_y, test_size=0.2)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

model = Sequential()
model.add(Dense(256, input_shape=(4,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

model.compile(optimizer='adam', loss='categorical_crossentropy',
             metrics=['accuracy'])
fit_hist = model.fit(X_train, Y_train, epochs=10, batch_size=50,
                     validation_data=(X_test, Y_test), verbose=1)

score = model.evaluate(X_test, Y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

plt.plot(fit_hist.history['val_accuracy'])
plt.plot(fit_hist.history['accuracy'])
plt.show()