# -*- coding: utf-8 -*-
"""AI_Exam1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9nszpmh0pzDJ41EiO5wqLcIPwvkTe_3
"""

def celsius_to_fahrenheit(x):
  return x * 1.8 + 32

celsius_value = int(input('섭씨온도를 입력하세요.'))
print('화씨온도로', celsius_to_fahrenheit(celsius_value), '입니다.')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
import numpy as np
import matplotlib.pyplot as plt

data_C = np.array(range(0,100))
data_F = celsius_to_fahrenheit(data_C)
print(data_C)
print(data_F)

model = Sequential()
model.add(InputLayer(input_shape=(1,)))
model.add(Dense(1))
model.compile(loss='mse', optimizer='sgd')
model.summary()
scaled_data_C = data_C / 100
scaled_data_F = data_F / 100
print(scaled_data_C)
print(scaled_data_F)
print(model.predict(np.array([0.01])))

model.save('before_learning.h5')

import h5py

with h5py.File('before_learning.h5', 'r') as f:
  print(f['model_weights']['dense']['sequential']['dense'].keys())
  print(list(f['model_weights']['dense']['sequential']['dense']['kernel']))
  print(list(f['model_weights']['dense']['sequential']['dense']['bias']))

fit_hist = model.fit(scaled_data_C, scaled_data_F, epochs = 1000)

model.save('after_learning.h5')
with h5py.File('after_learning.h5', 'r') as f:
  print(f['model_weights']['dense']['sequential']['dense'].keys())
  print(list(f['model_weights']['dense']['sequential']['dense']['kernel']))
  print(list(f['model_weights']['dense']['sequential']['dense']['bias']))

celsius_value = int(input('섭씨온도를 입력하세요.'))
print('화씨온도로', model.predict(np.array([celsius_value / 100])) * 100, '입니다')
noise = np.random.normal(0, 0.05, 100)

noised_scaled_data_F = np.array([])
for data in scaled_data_F:
  noised_scaled_data_F = np.append(noised_scaled_data_F, data + np.array(np.random.normal(0, 0.05, 100)))
print(noised_scaled_data_F)
print(len(noised_scaled_data_F))

noised_scaled_data_C = np.array([])
for data in scaled_data_C:
  for i in range(100):
    noised_scaled_data_C = np.append(noised_scaled_data_C, data)
print(noised_scaled_data_C)
print(len(noised_scaled_data_C))

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

# 노이즈 데이터 산점도
plt.scatter(noised_scaled_data_C, noised_scaled_data_F,
            s=1, alpha=0.3, label='Noisy data')


plt.xlabel('Scaled Celsius')
plt.ylabel('Scaled Fahrenheit')
plt.title('Noisy Celsius-Fahrenheit Data')
plt.legend()
plt.grid(True)
plt.show()

model2 = Sequential()
model2.add(InputLayer(input_shape=(1,)))
model2.add(Dense(1))
model2.compile(loss='mse', optimizer='sgd')
model2.summary()

print(model2.predict(np.array([0.01])))

fit_hist = model2.fit(noised_scaled_data_C, noised_scaled_data_F, epochs=20)
model2.save('noised_after_learning.h5')

print(model2.predict(np.array([0.01])))

with h5py.File('noised_after_learning.h5', 'r') as f:
  print(f['model_weights']['dense_1']['sequential_1']['dense_1'].keys())
  print(list(f['model_weights']['dense_1']['sequential_1']['dense_1']['kernel']))
  print(list(f['model_weights']['dense_1']['sequential_1']['dense_1']['bias']))

with h5py.File('before_learning.h5', 'r') as f:
    f.visit(print)

