# -*- coding: utf-8 -*-
"""AI_exam07_classification_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgXvvm_Lm6QOE4s5s-TfqC5nvauc5DLJ
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.utils import to_categorical
from tensorflow.keras import datasets

(X_train, Y_train), (X_test, Y_test) = datasets.mnist.load_data()
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

my_sample = np.random.randint(0, 60000)
plt.imshow(X_train[my_sample], cmap='gray')
plt.show()
print(Y_train[my_sample])
print(X_train[my_sample])

y_train = to_categorical(Y_train)
y_test = to_categorical(Y_test)
print(y_train.shape)
print(y_test.shape)

print(Y_train[0])
print(y_train[0])

x_train = X_train.reshape(60000, 784)
x_test = X_test.reshape(10000, 784)
x_train = x_train / 255
x_test = x_test / 255
print(x_train.shape)
print(x_test.shape)

model = Sequential()
model.add(Dense(128, input_dim=784, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer='adam', metrics=['accuracy'])
fit_hist = model.fit(x_train, y_train, batch_size=128,
                     epochs=15, validation_split=0.2, verbose=1)

score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

plt.plot(fit_hist.history['accuracy'])
plt.plot(fit_hist.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.show()

my_sample = np.random.randint(0, 10000)
plt.imshow(X_test[my_sample], cmap='gray')
plt.show()
print(Y_test[my_sample])
pred = model.predict(x_test[my_sample].reshape(-1, 784))
print(np.argmax(pred))
print(pred)

x_test[0].shape

