# -*- coding: utf-8 -*-
"""AI_exam05_titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOoo8x-N6mpM2YZtaZNBmSkSmzG2dESe
"""

import seaborn as sns
import pandas as pd
import numpy as np

raw_data = sns.load_dataset('titanic')
print(raw_data.head(50))

print(raw_data.info())

raw_data.isnull().sum()

mean_age = raw_data['age'].mean()
print(mean_age)
raw_data['age'].fillna(mean_age, inplace=True)
# raw_data.fillna({'age' : mean_age}, inplace=True)
print(raw_data.head(50))

raw_data.isnull().sum()

raw_data.loc[raw_data['age'] < 10, 'survived'].mean()

raw_data.survived.mean()

raw_data['sex'].value_counts()

raw_data.loc[raw_data['sex'] == 'male', 'survived'].mean()

raw_data.loc[raw_data['sex'] == 'female', 'survived'].mean()

raw_data.loc[raw_data['age'] > 60, 'survived'].mean()

raw_data.loc[raw_data['pclass'] == 1, 'survived'].mean()

raw_data.loc[((raw_data['pclass'] == 1) & (raw_data['sex'] == 'male')), 'survived'].mean()

raw_data.loc[((raw_data['pclass'] == 2) & (raw_data['sex'] == 'male')), 'survived'].mean()

raw_data.loc[((raw_data['pclass'] == 3) & (raw_data['sex'] == 'male')), 'survived'].mean()

raw_data.loc[((raw_data['pclass'] == 1) & (raw_data['sex'] == 'female')), 'survived'].mean()

raw_data.loc[((raw_data['pclass'] == 2) & (raw_data['sex'] == 'female')), 'survived'].mean()

raw_data.loc[((raw_data['pclass'] == 3) & (raw_data['sex'] == 'female')), 'survived'].mean()

clean_data = raw_data.drop(['embark_town', 'alive', 'class'], axis=1)
print(clean_data.info())

print(clean_data['embarked'][825:835])

clean_data['embarked'].fillna(method='ffill', inplace=True)
# clean_data['embarked'].fillna('ffill', inplace=True)
print(clean_data['embarked'][825:835])


clean_data = clean_data.dropna(axis=1, thresh=500)
print(clean_data.info())

clean_data['sex'].replace({'male': 0, 'female': 1}, inplace=True)
clean_data.info()

clean_data['embarked'].unique()

clean_data['embarked'].value_counts()

# clean_data['embarked'].replace({'S': 0, 'C': 1, 'Q':2}, inplace=True)

from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
clean_data['embarked'] = label_encoder.fit_transform(clean_data['embarked'])
print(clean_data['embarked'].unique())

label_encoder.classes_

clean_data.head(10)

label_encoder = preprocessing.LabelEncoder()
clean_data['who'] = label_encoder.fit_transform(clean_data['who'])
print(clean_data['who'].unique())

clean_data.info()

clean_data['adult_male'] = clean_data['adult_male'].astype('int64')
clean_data['alone'] = clean_data['alone'].astype('int64')
clean_data.info()

target = clean_data['survived']
clean_data = clean_data.drop(['survived'], axis=1)

clean_data.head()

value_data = ['age', 'fare']
df_value = clean_data[value_data]
df_value.info()

dummies = clean_data.drop(value_data, axis=1)
dummies.info()

df_dummies = pd.get_dummies(dummies, columns=dummies.columns, dtype=int)
df_dummies.info()

df_dummies.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_value)
scaled_data = pd.DataFrame(scaled_data, columns=df_value.columns)
print(scaled_data.head())
scaled_data.info()

traing_data = pd.concat([scaled_data, df_dummies], axis=1)
print(traing_data.head())
traing_data.info()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(traing_data, target,
                                                    test_size=0.2)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(128, input_dim=31, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_binary_accuracy',
    patience=5,
    mode='max',
    restore_best_weights=True
)

model.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['binary_accuracy'])
fit_hist = model.fit(X_train, y_train, epochs=30, batch_size=50,
        validation_split=0.2, callbacks=[early_stopping], verbose=1)

import matplotlib.pyplot as plt
plt.plot(fit_hist.history['loss'])
plt.plot(fit_hist.history['val_loss'])
plt.legend(['loss', 'val_loss'])
plt.show()

plt.plot(fit_hist.history['binary_accuracy'])
plt.plot(fit_hist.history['val_binary_accuracy'])
plt.legend(['binary_accuracy', 'val_binary_accuracy'])
plt.show()

score = model.evaluate(X_test, y_test)
print(score)

