# -*- coding: utf-8 -*-
"""AI_exam04_heart_disease_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JG_HMFH8mcy7glSsqMMoWhqJ0lJjXZfL
"""

import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input

"""age : 나이

sex : 성별

cp : 가슴 통증 종류

treshbps : 안정시 혈압

chol : 콜레스테롤

fbs : 공복시 혈당 (1:120초과,2:120이하)

restecg : 안정시 심전도 0:normal, 1:ST-T파 이상, 2:좌심실 비대

thalach : 최대 심박수

exang : 운동 유발 협심증 1:yes, 0:no

oldpeak : ST depression induced by exercise relative to rest

slope : the slope of the peak exercise ST segment 1:upsloping, 2:flat, 3:downsloping

ca : 조영제에 착색된 혈관수

thal : 3:normal, 6:고정 결함, 7:가역적 결함

HeartDisease : 심장병 유무
"""

column_name = ['age', 'sex', 'cp', 'treshbps',
               'chol', 'fbs', 'restecg', 'thalach',
               'exang', 'oldpeak', 'slope', 'ca',
               'thal', 'Heart_Disease']
raw_data = pd.read_excel('./ML_Data/heart-disease.xlsx', header=None, names=column_name)
print(raw_data.head(20))

print(raw_data.describe())

print(raw_data.info())

clean_data = raw_data.replace('?', np.nan)
clean_data = clean_data.dropna()
print(clean_data.info())

print(column_name)
keep = column_name.pop()
print(keep)
print(column_name)

training_data = clean_data[column_name]
print(training_data.head())
target = clean_data[[keep]]
print(target.head())

print(target.sum())

print(target.mean())

from sklearn.preprocessing import StandardScaler, MinMaxScaler, Normalizer
scaler = StandardScaler()
scaled_training_data = scaler.fit_transform(training_data)
scaled_training_data = pd.DataFrame(scaled_training_data, columns=column_name)
print(scaled_training_data)

print(scaled_training_data.describe().T)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
    train_test_split(scaled_training_data, target, test_size=0.2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

model = Sequential()
model.add(Input(shape=(13,)))
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(units=256, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(0.125))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.125))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

model.compile(loss='mse', optimizer='adam', metrics=['binary_accuracy'])
fit_hist = model.fit(X_train, y_train, epochs=30, batch_size=50,
                     validation_split=0.2, verbose=1)

plt.plot(fit_hist.history['binary_accuracy'])
plt.plot(fit_hist.history['val_binary_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

score = model.evaluate(X_test, y_test, verbose=0)
print('Keras DNN model loss', score[0])
print('Keras DNN model accuracy', score[1])

model.save('heart_disease_classification_model.keras')

from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.1)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))